//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resto_bar_web
{
    public partial class InsumoForm
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Literal litMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipo;
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPrecio;
        protected global::System.Web.UI.WebControls.RangeValidator rvPrecio;
        protected global::System.Web.UI.WebControls.TextBox txtStock;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStock;
        protected global::System.Web.UI.WebControls.RangeValidator rvStock;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
