//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resto_bar_web
{
    public partial class MesasAsignacion
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Literal litMensaje;
        protected global::System.Web.UI.WebControls.Panel pnlExito;
        protected global::System.Web.UI.WebControls.Literal litExito;
        protected global::System.Web.UI.WebControls.DropDownList ddlMesa;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMesa;
        protected global::System.Web.UI.WebControls.DropDownList ddlMesero;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMesero;
        protected global::System.Web.UI.WebControls.Button btnAsignar;
        protected global::System.Web.UI.WebControls.GridView dgvAsignadas;
    }
}
