//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resto_bar_web
{
    public partial class PedidoDetalle
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;

        protected global::System.Web.UI.WebControls.Literal litResumen;

        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        protected global::System.Web.UI.WebControls.Literal litMensaje;

        protected global::System.Web.UI.WebControls.Panel pnlExito;

        protected global::System.Web.UI.WebControls.Literal litExito;

        protected global::System.Web.UI.WebControls.Panel pnlCargaItem;

        protected global::System.Web.UI.WebControls.DropDownList ddlInsumo;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvInsumo;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCantidad;

        protected global::System.Web.UI.WebControls.RangeValidator rvCantidad;

        protected global::System.Web.UI.WebControls.Button btnAgregar;

        protected global::System.Web.UI.WebControls.GridView dgvDetalle;

        protected global::System.Web.UI.WebControls.Literal litTotal;

        protected global::System.Web.UI.WebControls.Button btnCerrar;
    }
}
